# Generated by Django 4.2.2 on 2023-07-02 09:03

import apps.lib.utils.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="admin",
            field=models.CharField(default="0", max_length=64),
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.lib.utils.functions.custom_id,
                        editable=False,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("creation_time", models.DateTimeField(auto_now=True)),
                (
                    "team_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="home.team"
                    ),
                ),
            ],
        ),
    ]
