# Generated by Django 4.2.2 on 2023-07-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_team_admin_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
