# Generated by Django 4.2.2 on 2023-07-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="creation_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
