# Generated by Django 4.2.2 on 2023-07-03 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_customuser_username"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="teams",),
        migrations.AddField(
            model_name="team",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="team",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
