# Generated by Django 4.2.2 on 2023-07-03 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_team_admin_alter_team_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
