# Generated by Django 4.2.2 on 2023-07-03 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_team_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="end_time",
            field=models.DateTimeField(default="2000-01-01 00:00:00.000000"),
        ),
        migrations.AddField(
            model_name="board",
            name="status",
            field=models.CharField(
                choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                default="OPEN",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="name",
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="board",
            name="team_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="boards",
                to="home.team",
            ),
        ),
    ]
