# Generated by Django 4.2.2 on 2023-07-04 08:47

import apps.lib.utils.functions
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_board_end_time_board_status_alter_board_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("CLOSED", "Closed"),
                    ("INACTIVE", "Inactive"),
                ],
                default="OPEN",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.lib.utils.functions.custom_id,
                        editable=False,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("creation_time", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETE", "Complete"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                ("end_time", models.DateTimeField()),
                (
                    "board_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="board_tasks",
                        to="home.board",
                    ),
                ),
                (
                    "team_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="team_tasks",
                        to="home.team",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
