# Generated by Django 4.2.2 on 2023-07-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_board_status_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="name",
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="board", unique_together={("team_id", "name")},
        ),
    ]
