# Generated by Django 4.2.2 on 2023-07-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_board_name_alter_board_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="task", unique_together={("board_id", "title")},
        ),
    ]
