# Generated by Django 4.2.2 on 2023-07-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_task_title_alter_task_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(name="board", options={"ordering": ("team_id",)},),
        migrations.AlterModelOptions(
            name="task", options={"ordering": ("team_id", "board_id", "user_id")},
        ),
        migrations.AlterField(
            model_name="board",
            name="end_time",
            field=models.DateTimeField(default="2000-01-01 00:00:00.000000+00:00"),
        ),
    ]
