# Generated by Django 4.2.2 on 2023-07-04 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_board_options_alter_task_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="board_id",
            field=models.ForeignKey(
                default="0000",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="board_tasks",
                to="home.board",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="user_id",
            field=models.ForeignKey(
                default="0000",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="user_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
