# Generated by Django 4.2.2 on 2023-07-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_task_board_id_alter_task_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task", name="end_time", field=models.DateTimeField(null=True),
        ),
    ]
