# Generated by Django 4.2.2 on 2023-07-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_alter_task_end_time"),
    ]

    operations = [
        migrations.AlterModelOptions(name="task", options={"ordering": ("-user_id",)},),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
