# Generated by Django 4.2.2 on 2023-07-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_alter_task_options_alter_team_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task", options={"ordering": ("team_id", "board_id", "-user_id")},
        ),
    ]
