# Generated by Django 4.2.2 on 2023-07-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("team_id", "board_id", "-user_id", "creation_time")},
        ),
    ]
